### ISSUE TITLE
Interested in hosting this on Wikimedia's Tool Labs?

### ISSUE THREAD

**Issue by bd808** [tomayac/wikipedia-edits-server-sent-events#1]
This is a neat project using Wikimedia data. Thanks for building it!

The [Tool Labs](https://wikitech.wikimedia.org/wiki/Portal:Tool_Labs) project at Wikimedia is provides free hosting for project like this that advance the Wikimedia movement. I think this project would be a good fit for hosting as a [Kubernetes webservice](https://wikitech.wikimedia.org/wiki/Help:Tool_Labs/Web/Kubernetes) on our platform. Our nodejs Docker containers provide nodejs v6.9.1 and our front-end proxy would provide https termination. If you are interested, I'd be glad to help you get started there. It would be a good excuse to write a nodejs+kubernetes tutorial.

**Comment by tomayac** [comment]
Duh, sorry, @bd808, I realize I never reacted to this issue :-( Personally I am quite constrained time-wise, but do feel free to just clone or fork the repo and make the necessary changes in order to run this on Tool Labs.

That being said, I have just have updated my [Wikipedia Screensaver](https://tomayac.github.io/wikipedia-screensaver/dist/) and migrated it to use the new [EventStreams](https://wikitech.wikimedia.org/wiki/EventStreams) service, so the [SSE implementation](https://wikipedia-edits.herokuapp.com/sse) based on the IRC stream from this project is mostly there for historical reasons now (it's still working, as the IRC stream is still up).

I'm closing this issue. Apologies again for not reacting (earlier).
